# Adds a label depending on the files/ directories that were changed. Makes it easier for us to determine
# who should be looking at it

ci/cd:
  - .github/workflows/*

documentation:
  - README.md
  - ./*.md

demodata:
  - demoData

olc:
  - src/olc_net/*

pre:
  - src/pre_net/*