name: OpenFHE Issue Template
description: Use this template to report any issue
title: "[Bug]: "
labels: [ "bug", "triage" ]
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: false
      options:
        - Bug
        - Build/Install
        - Performance
        - Support
        - Feature Request
        - Documentation Feature Request
        - Documentation Bug
        - Others
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please make sure that this is a bug. All help requests should be directed to [OpenFHE Discourse](https://openfhe.discourse.group/c/user-questions/17)

  - type: input
    id: version
    attributes:
      label: OpenFHE Version
      description: What version of OpenFHE was installed?
      placeholder: ex,. OpenFHE `X.Y.Z` where `X` is the major version, `Y` is the minor version, and `Z` is the patch version. This information can be found in the `CMakeLists.txt` file.
    validations:
      required: true


  - type: dropdown
    id: support
    attributes:
      label: Is this an official OpenFHE product?
      options:
        - "Yes"
        - "No"


  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      description: Please list your OS and distribution
      placeholder: e.g., Linux Ubuntu 16.04
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Compiler and Version
      description: Please list your compiler and the version number
      placeholder: e.g., gcc-12
    validations:
      required: false

  - type: input
    id: build-information
    attributes:
      label: CMake Output
      description: Copy-paste the output of a fresh `CMake` run
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: Current Behaviour?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
      render: shell
    validations:
      required: true

  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Standalone code to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/Jupyter/any notebook.
      placeholder: Tell us what you see!
      render: shell
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell